version: "3"
services:
  # client:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:80"
  db:
    image: mysql:8.0
    # cap_add:
    #   - SYS_NICE
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
      - ./db/dogs:/var/lib/mysql-files/dogs
volumes:
  db:
    driver: local