version: "3"
services:
  client:
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - GRAPHQL_BACKEND_URL=http://localhost:8888/.netlify/functions/graphql
    depends_on:
      - server
  server:
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    restart: always
    command: --init-file /data/application/init.sql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
      - ./db/dogs:/var/lib/mysql-files/dogs
volumes:
  db:
    driver: local